"""
lexer.py

Implements the lexical analyzer (lexer) for the Pulse programming language.

The lexer is responsible for reading the raw source code of a Pulse program
and converting it into a sequence of tokens. This process, known as lexical
analysis, breaks the continuous stream of characters into meaningful units
such as identifiers, keywords, literals, operators, and punctuation.

The lexer scans the input source code character by character and groups
characters into tokens based on the lexical rules of the language. It also
tracks line information to assist with accurate error reporting.

This module primarily provides:
- The Lexer class, which performs the scanning process.
- Logic for recognizing different token types such as numbers, strings,
    identifiers, keywords, and operators.
- Handling of whitespace, indentation, and newline tokens required for
    block structure in Pulse.

The tokens generated by the lexer are later consumed by the parser to
construct the Abstract Syntax Tree (AST) representing the program structure.
"""

from __future__ import annotations
from typing import Any
from src.tokens import TokenType, Token, KEYWORDS
from src.error import report_error, PulseLexError

# -------------------------------------------------------
# Lexer Class
# -------------------------------------------------------
class Lexer:
    """
    The Lexer class scans source code and produces a list of tokens.
    It handles whitespace, comments, strings, numbers, identifiers, keywords,
    operators, and special tokens like indentation and tensor literals.
    """
    
    _SINGLE_CHAR_TOKENS: dict[str, TokenType] = {
        '(': TokenType.LEFT_PAREN,
        ')': TokenType.RIGHT_PAREN,
        '[': TokenType.LEFT_BRACKET,
        ']': TokenType.RIGHT_BRACKET,
        '{': TokenType.LEFT_BRACE,
        '}': TokenType.RIGHT_BRACE,
        '%': TokenType.MODULUS,
        ',': TokenType.COMMA,
        ':': TokenType.COLON,
        ';': TokenType.SEMICOLON,
        '.': TokenType.DOT,
    }
    
    _COMPOUND_OPERATORS: dict[str, tuple[TokenType, TokenType]] = {
        '+': (TokenType.PLUS_EQUAL, TokenType.PLUS),
        '-': (TokenType.MINUS_EQUAL, TokenType.MINUS),
        '*': (TokenType.STAR_EQUAL, TokenType.STAR),
        '/': (TokenType.SLASH_EQUAL, TokenType.SLASH),
    }
    
    _ESCAPE_MAP: dict[str, str] = {
        'n':  '\n',
        't':  '\t',
        'r':  '\r',
        '\\': '\\',
        '"':  '"',
        "'":  "'",
    }
    
    def __init__(self, source: str) -> None:
        self.source = source
        self.tokens = []
        self.start = 0
        self.current = 0
        self.line = 1
        self.indent_stack = [0]


    # -------------------------------------------------------
    # Public Methods
    # -------------------------------------------------------
    def scan_tokens(self) -> list[Token]:
        """Main method to scan the entire source and return tokens list."""
        while not self.is_at_end():
            self.start = self.current
            self.scan_token()

        # Close any remaining indents
        while len(self.indent_stack) > 1:
            self.indent_stack.pop()
            self.add_token(TokenType.DEDENT)
        
        # Append EOF token
        self.tokens.append(Token(TokenType.EOF, "", None, self.line, self.column()))
        return self.tokens

    def scan_token(self) -> None:
        """Scans a single lexeme and adds the corresponding token."""
        c = self.advance()

        # Newline and Indentation
        if c == '\n':
            self.line += 1
            self.handle_indentation()

            # Emit NEWLINE only if last token is not NEWLINE / INDENT / DEDENT
            if self.tokens and self.tokens[-1].type not in (
                TokenType.NEWLINE,
                TokenType.INDENT,
                TokenType.DEDENT,
            ):
                self.add_token(TokenType.NEWLINE)
            return

        # Skip Comments
        if c == "#":
            while self.peek() not in ['\n', '\0'] and not self.is_at_end():
                self.advance()
            return
        
        # Tensor literal
        if c == '@' and self.peek() == '[':
            self.tensor_literal( )
            return
        
        # Skip Whitespace character
        if c in (" ", "\r", "\t"):
            return

        # Strings literal
        if c in ('"', "'"):
            self.string(c)
            return
        
        # Numbers literal
        if c.isdigit():
            self.number()
            return
        
        # Identifier or Keyword
        if c.isalpha() or c == "_":
            self.identifier()
            return
        
        # Multi-character operators
        if c == "!":
            if self.match("="):
                self.add_token(TokenType.BANG_EQUAL)
            else:
                raise PulseLexError(
                    message="Unexpected '!' without '='",
                    line=self.line,
                    column=self.column(),
                    context=self.source.splitlines()[self.line-1]
                )
            return
        
        if c in self._COMPOUND_OPERATORS:
            with_eq, without_eq = self._COMPOUND_OPERATORS[c]
            self.add_token(with_eq if self.match('=') else without_eq)
            return
        
        if c == "<":
            self.add_token(TokenType.LESS_EQUAL if self.match("=") else TokenType.LESS)
            return
        
        if c == ">":
            self.add_token(TokenType.GREATER_EQUAL if self.match("=") else TokenType.GREATER)
            return
        
        if c == "=":
            self.add_token(TokenType.EQUALITY if self.match("=") else TokenType.ASSIGN)
            return
        
        # Single-character tokens
        if c in self._SINGLE_CHAR_TOKENS:
            self.add_token(self._SINGLE_CHAR_TOKENS[c])
            return

        # Unexpected character
        raise PulseLexError(
            message="Unexpected character", 
            line=self.line, 
            column=self.column(),
            context=self.source.splitlines()[self.line-1]
        )
    
    def handle_indentation(self) -> None:
        """
        Handles spaces at the start of a line to generate INDENT/DEDENT tokens.
        Tab are not allowed.
        """
        spaces = 0
        pos = self.current

        # Count leading spaces
        while pos < len(self.source):
            ch = self.source[pos]
            if ch == ' ':
                spaces += 1
            elif ch == '\t':
                raise PulseLexError(
                    message="Tabs are not allowed for identation", 
                    line=self.line,
                    column=self.column(),
                    context=self.source.splitlines()[self.line-1]
                )
            else:
                break
            pos += 1

        # Skip completely blank lines or comment lines
        if pos >= len(self.source) or self.source[pos] in ('\n', '#'):
            return

        last_indent = self.indent_stack[-1]

        if spaces > last_indent:
            self.indent_stack.append(spaces)
            self.start = self.current
            self.add_token(TokenType.INDENT)
        elif spaces < last_indent:
            if spaces not in self.indent_stack:
                raise PulseLexError(
                    message="Invalid indentation level", 
                    line=self.line,
                    column=self.column(),
                    context=self.source.splitlines()[self.line-1]
                )
            while self.indent_stack and spaces < self.indent_stack[-1]:
                self.indent_stack.pop()
                self.start = self.current
                self.add_token(TokenType.DEDENT)

        # Move current pointer past indentation
        self.current = pos
    
    def string(self, quote_type) -> None:
        """Handles string literals enclosed in double and single quotes"""
        value_chars = []
        
        while not self.is_at_end():
            c = self.advance()
            
            if c == quote_type:
                break
            
            if c == "\\":
                if self.is_at_end():
                    break
                nxt = self.advance()
                value_chars.append(self._ESCAPE_MAP.get(nxt, nxt))
            else:
                if c == "\n":
                    self.line += 1
                value_chars.append(c)
        else:
            raise PulseLexError(
                message="Unterminated string",
                line=self.line,
                column=self.column(),
                context=self.source.splitlines()[self.line-1]
            )
        
        self.add_token(TokenType.STRING, "".join(value_chars))
    
    def number(self) -> None:
        """Handles integer and floating-point number literals."""
        while self.peek().isdigit():
            self.advance()
        
        # Fractional part
        if self.peek() == '.' and self.peek_next().isdigit():
            self.advance()
            while self.peek().isdigit():
                self.advance()
        
        text = self.source[self.start:self.current]
        value = float(text) if "." in text else int(text)
        self.add_token(TokenType.NUMBER, value)

    def identifier(self) -> None:
        """Handles identifiers and keywords."""
        while self.peek().isalnum() or self.peek() == '_':
            self.advance()
        
        text = self.source[self.start : self.current]
        
        if text in ("true", "false"):
            self.add_token(TokenType.BOOL, literal=(text=="true"))
            return
        
        if text == "null":
            self.add_token(TokenType.NULL, literal=None)
            return
        
        if text == "self":
            self.add_token(TokenType.SELF)
            return
        
        token_type = KEYWORDS.get(text, TokenType.IDENTIFIER)
        self.add_token(token_type)

    # No strings allowed inside tensors for now
    def tensor_literal(self) -> None:
        """Handles multi-dimensional tensor literals prefixed with '@'."""
        self.start = self.current - 1
        depth = 0

        if self.peek() != '[':
            raise PulseLexError(
                message="Expected '[' after '@'", 
                line=self.line,
                column=self.column(),
                context=self.source.splitlines()[self.line-1]
            )
        
        while not self.is_at_end():
            ch = self.advance()

            if ch == '"':
                raise PulseLexError(
                    message="Strings are not allowed inside tensor literals", 
                    line=self.line,
                    column=self.column(),
                    context=self.source.splitlines()[self.line-1]
                )

            if ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    break

        if depth != 0:
            raise PulseLexError(
                message="Unterminated tensor literal", 
                line=self.line, 
                column=self.column(),
                context=self.source.splitlines()[self.line-1]
            )

        # Capture entire tensor WITHOUT @
        value = self.source[self.start+1 : self.current]
        self.add_token(TokenType.TENSOR_LITERAL, value)

    # -------------------------------------------------------
    # Utility Methods
    # -------------------------------------------------------
    def is_at_end(self) -> bool:
        """Checks if the lexer has reached the end of the source."""
        return self.current >= len(self.source)

    def peek(self) -> str:
        """Returns the current character without consuming it."""
        return '\0' if self.is_at_end() else self.source[self.current]

    def peek_next(self) -> str:
        """Returns the next character without consuming it."""
        if self.current + 1 >= len(self.source):
            return '\0'
        return self.source[self.current + 1]

    def advance(self) -> str:
        """Consume and returns the current character."""
        char = self.source[self.current]
        self.current += 1
        return char
    
    def add_token(self, type, literal=None) -> None:
        """Creates a token and appends it to the token list."""
        if type is None:
            raise PulseLexError(
                message="Invalid operator", 
                line=self.line, 
                column=self.column(),
                context=self.source.splitlines()[self.line-1]
            )
        lexeme = self.source[self.start:self.current]
        if type == TokenType.NEWLINE:
            lexeme = "\\n"
        if type == TokenType.DEDENT:
            lexeme = ""
        self.tokens.append(Token(type, lexeme, literal, self.line, self.column()))

    def match(self, expected) -> bool:
        """Matches the next character if it equals 'expected' and consumes it."""
        if self.is_at_end() or self.source[self.current] != expected:
            return False
        self.current += 1
        return True
    
    def column(self) -> int:
        """Returns the column number of current character in the line."""
        last_newline = self.source.rfind('\n', 0, self.current)
        return self.current - last_newline - 1

# -------------------------------------------------------
# Command-line Interface
# -------------------------------------------------------
if __name__ == "__main__":
    import sys
    path = sys.argv[1]

    if not path.endswith(".pul"):
        raise Exception(f'"{path}" is not a .pul file. Pulse only reads .pul, behave.')
    
    with open(path) as f:
        source = f.read()

    lexer = Lexer(source)
    tokens = lexer.scan_tokens()

    for token in tokens:
        print(token)