"""
parser.py

Implements the parser for the Pulse programming language.

The parser receives a sequence of tokens generated by the lexer and
constructs an Abstract Syntax Tree (AST) representing the syntactic
structure of a Pulse program. Using a rule-based parsing approach,
it validates the arrangement of tokens according to the grammar of
the language and converts them into structured AST nodes.

The parser is responsible for recognizing language constructs such as
expressions, variable assignments, control flow statements, function
definitions, and other syntactic elements supported by Pulse.

This module primarily provides:
- The Parser class, which consumes tokens sequentially and applies
    grammar rules to build the AST.
- Methods that correspond to grammar productions for expressions,
    statements, and program blocks.
- Error detection and synchronization mechanisms to handle
    invalid syntax gracefully during parsing.

The resulting AST is later used by the interpreter or compiler to
execute or further process the Pulse program.
"""

from __future__ import annotations
from typing import List, Optional, Tuple
from src import expressions as expr
from src import statements as stmt
from src.tokens import Token, TokenType
from src.error import PulseSyntaxError
from src.lexer import Lexer

class ParseError(PulseSyntaxError):
    def __init__(self, token: Token, message: str, source: str) -> None:
        line = token.line        
        context = None

        if line is not None:
            lines = source.splitlines()
            if 0 < line <= len(lines):
                context = lines[line - 1]
        
        super().__init__(message, line=line, context=context)

class Parser:
    def __init__(self, tokens: List[Token], source: str) -> None:
        self.tokens = tokens
        self.source = source
        self.current = 0
    
    # Core helper functions
    def peek(self) -> Token:
        return self.tokens[self.current]
    
    def peek_next(self) -> Token:
        if self.current + 1 >= len(self.tokens):
            return self.tokens[-1]
        return self.tokens[self.current + 1]
    
    def previous(self) -> Token:
        return self.tokens[self.current - 1]
    
    def is_at_end(self) -> bool:
        return self.peek().type == TokenType.EOF
    
    def advance(self) -> Token:
        if not self.is_at_end():
            self.current += 1
        return self.previous()
    
    def check(self, typ: TokenType) -> bool:
        if self.is_at_end():
            return False
        return self.peek().type == typ
    
    def match(self, *types: TokenType) -> bool:
        for t in types:
            if self.check(t):
                self.advance()
                return True
        return False
    
    def consume(self, type: TokenType, message: str) -> Token:
        if self.check(type):
            return self.advance()
        raise ParseError(self.peek(), message, self.source)
    
    # Entry
    def parse(self) -> List[stmt.Stmt]:
        statements: List[stmt.Stmt] = []
        
        while not self.is_at_end():
            s = self.statement()
            if s is not None:
                statements.append(s)
        
        return statements
    
    def statement(self) -> Optional[stmt.Stmt]:
        if self.match(TokenType.INDENT):
            return self.block()
        
        if self.match(TokenType.DEF):
            return self.parse_func_stmt()
        if self.match(TokenType.CLASS):
            return self.parse_class_stmt()
        
        if self.match(TokenType.IF):
            return self.parse_if_stmt()
        if self.match(TokenType.WHILE):
            return self.parse_while_stmt()
        if self.match(TokenType.FOR):
            return self.parse_for_stmt()
        
        if self.match(TokenType.TRY):
            return self.parse_try_stmt()
        
        if self.match(TokenType.BREAK):
            return stmt.Break(self.previous())
        if self.match(TokenType.CONTINUE):
            return stmt.Continue(self.previous())
        if self.match(TokenType.RETURN):
            return self.parse_return_stmt()
        if self.match(TokenType.PASS):
            return stmt.Pass()
        
        # Skip empty statements
        if self.match(TokenType.NEWLINE):
            return None        
        # Stop parsing expressions if we hit block end
        if self.check(TokenType.DEDENT) or self.is_at_end():
            return None
        
        expr_stmt = self.expression()
        self.match(TokenType.NEWLINE)
        return stmt.Expression(expr_stmt)

    def block(self) -> stmt.Block:
        statements: List[stmt.Stmt] = []
        
        while not self.check(TokenType.DEDENT) and not self.is_at_end():
            s = self.statement()
            if s is not None:
                statements.append(s)
        
        self.consume(TokenType.DEDENT, "Block not closed")
        return stmt.Block(statements)
    
    def parse_if_stmt(self) -> stmt.If:
        condition = self.expression()
        self.consume(TokenType.COLON, "Expect ':' after condition")
        
        then_branch = self.statement()
        
        elif_branches = []
        while self.match(TokenType.ELIF):
            elif_condition = self.expression()
            self.consume(TokenType.COLON, "Expect ':' after condition")
            elif_stmt = self.statement()
            elif_branches.append((elif_condition, elif_stmt))
        
        else_branch = None
        if self.match(TokenType.ELSE):
            self.consume(TokenType.COLON, "Expect ':' after else")
            else_branch = self.statement()
        
        return stmt.If(condition, then_branch, elif_branches, else_branch)
    
    def parse_while_stmt(self) -> stmt.While:
        condition = self.expression()
        self.consume(TokenType.COLON, "Expected ':' after while condition")
        body = self.statement()
        return stmt.While(condition, body)
    
    def parse_for_stmt(self) -> stmt.For:
        var_token = self.consume(TokenType.IDENTIFIER, "Expected loop variable after 'for'")
        self.consume(TokenType.IN, "Expected 'in' after loop variable")
        iterable = self.expression()
        self.consume(TokenType.COLON, "Expected ':' after iterable")
        
        # Will work for loop depths later
        # self.loop_depth += 1
        body = self.statement()
        # self.loop_depth -= 1
        
        return stmt.For(var_token, iterable, body)
    
    def parse_func_stmt(self, is_method: bool = False, is_static: bool = False) -> stmt.Function:
        name = self.consume(TokenType.IDENTIFIER, "Expect function name.")
        self.consume(TokenType.LEFT_PAREN, "Expect '(' after function name.")
        
        params: List[Token] = []
        if not self.check(TokenType.RIGHT_PAREN):
            params.append(self._consume_param())
            while self.match(TokenType.COMMA):
                if self.check(TokenType.RIGHT_PAREN):
                    break
                params.append(self._consume_param())
        
        self.consume(TokenType.RIGHT_PAREN, "Expect ')' after parameters.")
        self.consume(TokenType.COLON, "Expect ':' before function body.")
        
        if is_static:
            for p in params:
                if p.type == TokenType.SELF:
                    raise ParseError(p, "Static method cannot have 'self'", self.source)
        
        if is_method and not is_static:
            if len(params) == 0 or params[0].type != TokenType.SELF:
                raise ParseError(name, "Instance method must have 'self' as first parameter", self.source)
        
        self.consume(TokenType.INDENT, "Expect block indentation")
        body = self.block()
        return stmt.Function(name, params, body, is_method)
    
    def _consume_param(self):
        if self.check(TokenType.SELF):
            return self.advance()
        return self.consume(TokenType.IDENTIFIER, "Expect parameter name.")
    
    def parse_class_stmt(self) -> stmt.Class:
        name = self.consume(TokenType.IDENTIFIER, "Expect class name")
        
        bases = []
        if self.match(TokenType.LEFT_PAREN):
            if not self.check(TokenType.RIGHT_PAREN):
                bases.append(self.consume(TokenType.IDENTIFIER, "Expect base class name"))
                while self.match(TokenType.COMMA):
                    if self.check(TokenType.RIGHT_PAREN):
                        break
                    bases.append(self.consume(TokenType.IDENTIFIER, "Expect base class name"))
            self.consume(TokenType.RIGHT_PAREN, "Expect ')' after base classes")
        
        self.consume(TokenType.COLON, "Expect ':' after class declaration")
        self.consume(TokenType.INDENT, "Expect class body indentation")
        
        methods: List[stmt.Function] = []
        static_methods: List[stmt.Function] = []
        class_vars: List[Tuple[Token, expr.Expr]] = []
        
        while not self.check(TokenType.DEDENT) and not self.is_at_end():
            if self.match(TokenType.NEWLINE):
                continue
            
            if self.match(TokenType.STATIC):
                self.consume(TokenType.DEF, "Expect 'def' after 'static'")
                method = self.parse_func_stmt(is_method=True, is_static=True)
                static_methods.append(method)
                continue
            
            if self.match(TokenType.DEF):
                method = self.parse_func_stmt(is_method=True, is_static=False)
                methods.append(method)
                continue
            
            if self.check(TokenType.IDENTIFIER):
                name_tok = self.consume(TokenType.IDENTIFIER, "Expect variable name")
                self.consume(TokenType.ASSIGN, "Expect '=' after variable name")
                
                value = self.expression()
                self.match(TokenType.NEWLINE)
                class_vars.append((name_tok, value))
                continue
            
            raise ParseError(self.peek(), "Invalid class body statement", self.source)
        
        self.consume(TokenType.DEDENT, "Class body not closed")
        return stmt.Class(name, bases, methods, static_methods, class_vars)
    
    def parse_try_stmt(self) -> stmt.Try:
        self.consume(TokenType.COLON, "Expected ':' after 'try'")
        try_block = self.statement()
        if try_block is None:
            raise ParseError(self.peek(), "Expected block after 'try'", self.source)
        
        except_blocks = []
        while self.match(TokenType.EXCEPT):
            exc_type = None
            exc_name = None
            if not self.check(TokenType.COLON):
                exc_type = self.expression()
                if self.match(TokenType.AS):
                    exc_name = self.consume(TokenType.IDENTIFIER, "Expected variable after 'as'")
            self.consume(TokenType.COLON, "Expected ':' after 'except'")
            block = self.statement()
            except_blocks.append((exc_type, exc_name, block))
        
        else_block = None
        if self.match(TokenType.ELSE):
            self.consume(TokenType.COLON, "Expected ':' after 'else'")
            else_block = self.statement()
        
        finally_block = None
        if self.match(TokenType.FINALLY):
            self.consume(TokenType.COLON, "Expected ':' after 'finally'")
            finally_block = self.statement()
        
        return stmt.Try(try_block, except_blocks, finally_block, else_block)
    
    def parse_return_stmt(self) -> stmt.Return:
        keyword = self.previous()
        
        value = None        
        if not (self.check(TokenType.NEWLINE) or self.check(TokenType.DEDENT) or self.is_at_end()):
            value = self.expression()
        
        self.match(TokenType.NEWLINE)
        return stmt.Return(keyword, value)
    
    def expression(self) -> expr.Expr:
        return self.assignment()
    
    def assignment(self) -> expr.Expr:
        left = self.logic()
        
        if self.match(TokenType.ASSIGN):
            value = self.assignment()
            
            # a = 5
            if isinstance(left, expr.Variable):
                return expr.Assign(left.name, value)
            
            # obj.x = 5
            if isinstance(left, expr.MemberAccess):
                return expr.SetMember(left.object, left.name, value)
            
            # a[0] = 5
            if isinstance(left, expr.Index):
                return expr.SetIndex(left.object, left.index, value)
            
            raise ParseError(self.previous(), "Invalid assignment target", self.source)
        
        return left
    
    def logic(self) -> expr.Expr:
        node = self.equality()
        
        while self.match(TokenType.AND, TokenType.OR):
            op = self.previous()
            right = self.equality()
            node = expr.Logical(node, op, right)
        
        return node
    
    def equality(self) -> expr.Expr:
        node = self.comparison()
        
        while self.match(TokenType.EQUALITY, TokenType.BANG_EQUAL):
            op = self.previous()
            right = self.comparison()
            node = expr.Binary(node, op, right)
        
        return node
    
    def comparison(self) -> expr.Expr:
        node = self.addition()
        
        while self.match(
            TokenType.GREATER,
            TokenType.GREATER_EQUAL,
            TokenType.LESS,
            TokenType.LESS_EQUAL,
        ):
            op = self.previous()
            right = self.addition()
            node = expr.Binary(node, op, right)
        
        return node
    
    def addition(self) -> expr.Expr:
        node = self.multiplication()
        
        while self.match(TokenType.PLUS, TokenType.MINUS):
            op = self.previous()
            right = self.multiplication()
            node = expr.Binary(node, op, right)
        
        return node
    
    def multiplication(self) -> expr.Expr:
        node = self.unary()
        
        while self.match(TokenType.STAR, TokenType.SLASH, TokenType.MODULUS, TokenType.INT_DIVIDE):
            op = self.previous()
            right = self.unary()
            node = expr.Binary(node, op, right)
        
        return node
    
    def unary(self) -> expr.Expr:
        if self.match(TokenType.MINUS, TokenType.NOT):
            op = self.previous()
            right = self.unary()
            return expr.Unary(op, right)
        
        return self.call()
    
    def call(self) -> expr.Expr:
        expr_node = self.primary()
        
        while True:
            if self.match(TokenType.LEFT_PAREN):
                arguments = []
                keyword_arguments = []
                
                if not self.check(TokenType.RIGHT_PAREN):
                    while True:
                        if self.check(TokenType.IDENTIFIER) and self.peek_next().type == TokenType.ASSIGN:
                            name = self.advance()
                            self.consume(TokenType.ASSIGN, "Expect '=' after keyword name")
                            value = self.expression()
                            keyword_arguments.append((name, value))
                        else:
                            arguments.append(self.expression())
                        if not self.match(TokenType.COMMA):
                            break
                
                paren = self.consume(TokenType.RIGHT_PAREN, "Expect ')' after arguments")
                expr_node = expr.Call(expr_node, paren, arguments, keyword_arguments)
            
            elif self.match(TokenType.DOT):
                name = self.consume(TokenType.IDENTIFIER, "Expect property name after '.'")
                expr_node = expr.MemberAccess(expr_node, name)
            
            elif self.match(TokenType.LEFT_BRACKET):
                index = self.expression()
                self.consume(TokenType.RIGHT_BRACKET, "Expect ']' after index")
                expr_node = expr.Index(expr_node, index)
            
            else:
                break
        
        return expr_node
    
    def primary(self) -> expr.Expr:
        if self.match(TokenType.LEFT_BRACE):
            return self.parse_dict_literal()
        
        if self.match(TokenType.LEFT_BRACKET):
            elements: List[expr.Expr] = []
            
            if not self.check(TokenType.RIGHT_BRACKET):
                elements.append(self.expression())
                while self.match(TokenType.COMMA):
                    if self.check(TokenType.RIGHT_BRACKET):
                        break
                    elements.append(self.expression())
            
            self.consume(TokenType.RIGHT_BRACKET, "Expect ']' after list")
            return expr.List(elements)
        
        if self.match(TokenType.SELF):
            return expr.Variable(self.previous())
        
        if self.match(TokenType.NULL):
            return expr.Literal(None)
        
        if self.match(TokenType.FSTRING):
            return self.parse_fstring(self.previous())
        
        if self.match(TokenType.NUMBER, TokenType.STRING, TokenType.BOOL):
            return expr.Literal(self.previous().literal)
        
        if self.match(TokenType.IDENTIFIER):
            return expr.Variable(self.previous())
        
        if self.match(TokenType.LEFT_PAREN):
            expr_node = self.expression()
            self.consume(TokenType.RIGHT_PAREN, "Expect ')' after expression")
            return expr_node
        
        raise ParseError(self.peek(), "Expect expression", self.source)
    
    def parse_dict_literal(self) -> expr.Dict:
        keys: List[expr.Expr] = []
        values: List[expr.Expr] = []
        
        if not self.check(TokenType.RIGHT_BRACE):
            while True:
                key = self.expression()
                self.consume(TokenType.COLON, "Expect ':' after dict key")
                value = self.expression()
                keys.append(key)
                values.append(value)
                if not self.match(TokenType.COMMA):
                    break
                if self.check(TokenType.RIGHT_BRACE):
                    break
        
        self.consume(TokenType.RIGHT_BRACE, "Expect '}' after dict entries")
        return expr.Dict(keys, values)
    
    def parse_fstring(self, token) -> expr.FString:
        raw = token.literal
        parts = []
        i = 0
        
        while i < len(raw):
            start = raw.find("{", i)
            
            if start == -1:
                if i < len(raw):
                    parts.append(expr.Literal(raw[i:]))
                break
            
            if start > i :
                parts.append(expr.Literal(raw[i:start]))
            
            end = raw.find("}", start)
            if end == -1:
                raise ParseError(token, "Unclosed '{' in f-string", self.source)
            
            fragment = raw[start + 1:end].strip()
            if not fragment:
                raise ParseError(token, "Empty expression in f-string", self.source)
            
            inner_tokens = Lexer(fragment).scan_tokens()
            inner_parser = Parser(inner_tokens, fragment)
            parts.append(inner_parser.expression())
            
            i = end + 1
        
        return expr.FString(parts)