"""
parser.py

Implements the parser for the Pulse programming language.

The parser receives a sequence of tokens generated by the lexer and
constructs an Abstract Syntax Tree (AST) representing the syntactic
structure of a Pulse program. Using a rule-based parsing approach,
it validates the arrangement of tokens according to the grammar of
the language and converts them into structured AST nodes.

The parser is responsible for recognizing language constructs such as
expressions, variable assignments, control flow statements, function
definitions, and other syntactic elements supported by Pulse.

This module primarily provides:
- The Parser class, which consumes tokens sequentially and applies
    grammar rules to build the AST.
- Methods that correspond to grammar productions for expressions,
    statements, and program blocks.
- Error detection and synchronization mechanisms to handle
    invalid syntax gracefully during parsing.

The resulting AST is later used by the interpreter or compiler to
execute or further process the Pulse program.
"""

from __future__ import annotations
from typing import List, Optional, Tuple
from src import expressions as expr
from src import statements as stmt
from src.tokens import Token, TokenType
from src.error import PulseSyntaxError
from src.lexer import Lexer
import ast as py_ast

class Parser:
    def __init__(self, tokens: List[Token], source: str) -> None:
        self.tokens = tokens
        self.source = source
        self.current = 0
        self.loop_depth = 0
    
    def _context(self, line: int | None) -> str | None:
        if not line:
            return None
        lines = self.source.splitlines()
        if 1 <= line <= len(lines):
            return lines[line - 1]
        return None
    
    def _error(self, token: Token, message: str) -> None:
        raise PulseSyntaxError(
            message=message,
            line=token.line,
            column=getattr(token, "column", None),
            context=self._context(token.line),
            filename="<pulse>"
        )
    
    # Core helper functions
    def peek(self) -> Token:
        return self.tokens[self.current]
    
    def peek_next(self) -> Token:
        if self.current + 1 >= len(self.tokens):
            return self.tokens[-1]
        return self.tokens[self.current + 1]
    
    def previous(self) -> Token:
        return self.tokens[self.current - 1]
    
    def is_at_end(self) -> bool:
        return self.peek().type == TokenType.EOF
    
    def advance(self) -> Token:
        if not self.is_at_end():
            self.current += 1
        return self.previous()
    
    def check(self, typ: TokenType) -> bool:
        if self.is_at_end():
            return False
        return self.peek().type == typ
    
    def match(self, *types: TokenType) -> bool:
        for t in types:
            if self.check(t):
                self.advance()
                return True
        return False
    
    def consume(self, type: TokenType, message: str) -> Token:
        if self.check(type):
            return self.advance()
        
        if self.current > 0:
            error_token = self.previous()
            error_token = Token(
                type=error_token.type,
                lexeme=error_token.lexeme,
                literal=error_token.literal,
                line=error_token.line,
                column=getattr(error_token, "column", 0) + len(error_token.lexeme),
            )
        else:
            error_token = self.peek()
        
        self._error(error_token, message)
        raise AssertionError("unreachable")
    
    # Entry
    def parse(self) -> List[stmt.Stmt]:
        statements: List[stmt.Stmt] = []
        
        while not self.is_at_end():
            s = self.statement()
            if s is not None:
                statements.append(s)
        
        return statements
    
    def statement(self) -> Optional[stmt.Stmt]:
        if self.match(TokenType.NEWLINE):
            return None
        if self.check(TokenType.DEDENT) or self.is_at_end():
            return None
        
        if self.match(TokenType.INDENT):
            return self.block()
        
        if self.check(TokenType.IDENTIFIER) and self.is_unpack_assignment():
            return self.parse_unpack_stmt()
        if self.match(TokenType.DEL):
            return self.parse_del_stmt()
        
        if self.match(TokenType.IMPORT):
            return self.parse_import_stmt()
        if self.match(TokenType.FROM):
            return self.parse_from_import_stmt()
        
        if self.match(TokenType.DEF):
            return self.parse_func_stmt()
        if self.match(TokenType.CLASS):
            return self.parse_class_stmt()
        
        if self.match(TokenType.IF):
            return self.parse_if_stmt()
        if self.match(TokenType.WHILE):
            return self.parse_while_stmt()
        if self.match(TokenType.FOR):
            return self.parse_for_stmt()
        if self.match(TokenType.MATCH):
            return self.parse_match_stmt()
        
        if self.match(TokenType.TRY):
            return self.parse_try_stmt()
        if self.match(TokenType.RAISE):
            return self.parse_raise_stmt()
        
        if self.match(TokenType.BREAK):
            keyword = self.previous()
            self.match(TokenType.NEWLINE)
            return stmt.Break(keyword)
        if self.match(TokenType.CONTINUE):
            keyword = self.previous()
            self.match(TokenType.NEWLINE)
            return stmt.Continue(keyword)
        if self.match(TokenType.RETURN):
            return self.parse_return_stmt()
        if self.match(TokenType.PASS):
            self.match(TokenType.NEWLINE)
            return stmt.Pass()
        
        expr_node = self.expression()
        self.match(TokenType.NEWLINE)
        return stmt.Expression(expr_node)
    
    def block(self) -> stmt.Block:
        statements: List[stmt.Stmt] = []
        
        while not self.check(TokenType.DEDENT) and not self.is_at_end():
            s = self.statement()
            if s is not None:
                statements.append(s)
        
        if self.is_at_end():
            self._error(self.previous(), "Unclosed block - expected DEDENT before end of file")
        
        self.consume(TokenType.DEDENT, "Expected end of block (DEDENT)")
        return stmt.Block(statements)
    
    def _expect_indented_block(self) -> stmt.Stmt:
        if not self.check(TokenType.INDENT):
            self._error(self.peek(), "Expected an indented block")
        return self.statement()
    
    def parse_if_stmt(self) -> stmt.If:
        condition = self.expression()
        self.consume(TokenType.COLON, "Expected ':' after if condition")
        then_branch = self._expect_indented_block()
        
        elif_branches: List[Tuple[expr.Expr, stmt.Stmt]] = []
        while self.match(TokenType.ELIF):
            elif_condition = self.expression()
            self.consume(TokenType.COLON, "Expected ':' after elif condition")
            elif_stmt = self._expect_indented_block()
            elif_branches.append((elif_condition, elif_stmt))
        
        else_branch = None
        if self.match(TokenType.ELSE):
            self.consume(TokenType.COLON, "Expected ':' after else")
            else_branch = self._expect_indented_block()
        
        return stmt.If(condition, then_branch, elif_branches, else_branch)
    
    def parse_while_stmt(self) -> stmt.While:
        condition = self.expression()
        self.consume(TokenType.COLON, "Expected ':' after while condition")
        self.loop_depth += 1
        body = self._expect_indented_block()
        self.loop_depth -= 1
        return stmt.While(condition, body)
    
    def parse_for_stmt(self) -> stmt.For:
        vars: List[Token] = []
        vars.append(self.consume(TokenType.IDENTIFIER, "Expected loop variable after 'for'"))
        while self.match(TokenType.COMMA):
            vars.append(self.consume(TokenType.IDENTIFIER, "Expected variable name after ','"))
        
        self.consume(TokenType.IN, "Expected 'in' after loop variable")
        iterable = self.expression()
        self.consume(TokenType.COLON, "Expected ':' after iterable")
        
        self.loop_depth += 1
        body = self._expect_indented_block()
        self.loop_depth -= 1
        
        var_token = vars[0]
        return stmt.For(var_token, iterable, body, vars if len(vars) > 1 else None)
    
    def parse_func_stmt(self, is_method: bool = False, is_static: bool = False) -> stmt.Function:
        name = self.consume(TokenType.IDENTIFIER, "Expected function name")
        self.consume(TokenType.LEFT_PAREN, "Expected '(' after function name")
        
        params: List[Token] = []
        defaults: List[Optional[expr.Expr]] = []
        vararg: Optional[Token] = None
        
        if not self.check(TokenType.RIGHT_PAREN):
            while True:
                if self.match(TokenType.STAR):
                    vararg = self.consume(TokenType.IDENTIFIER, "Expected parameter name after '*'")
                    if not self.check(TokenType.RIGHT_PAREN):
                        self.consume(TokenType.RIGHT_PAREN, "*args must be the last parameter")
                    break
                
                param, default = self._consume_param_with_default()
                if default is None and any(d is not None for d in defaults):
                    self._error(param, "Non-default parameter cannot follow a default parameter")
                params.append(param)
                defaults.append(default)
                
                if not self.match(TokenType.COMMA):
                    break
                if self.check(TokenType.RIGHT_PAREN):
                    break
        
        self.consume(TokenType.RIGHT_PAREN, "Expected ')' after parameters.")
        self.consume(TokenType.COLON, "Expected ':' before function body")
        
        self.consume(TokenType.INDENT, "Expected indented block after function definition")
        body = self.block()
        return stmt.Function(name, params, defaults, vararg, body, is_method, is_static)
    
    def _consume_param(self) -> Token:
        if self.check(TokenType.SELF):
            return self.advance()
        return self.consume(TokenType.IDENTIFIER, "Expected parameter name")
    
    def _consume_param_with_default(self) -> Tuple[Token, Optional[expr.Expr]]:
        if self.check(TokenType.SELF):
            return self.advance(), None
        param = self.consume(TokenType.IDENTIFIER, "Expected parameter name")
        default = None
        if self.match(TokenType.ASSIGN):
            default = self.expression()
        return param, default
    
    def parse_class_stmt(self) -> stmt.Class:
        name = self.consume(TokenType.IDENTIFIER, "Expected class name")
        
        bases: List[Token] = []
        if self.match(TokenType.LEFT_PAREN):
            if not self.check(TokenType.RIGHT_PAREN):
                bases.append(self.consume(TokenType.IDENTIFIER, "Expected base class name"))
                while self.match(TokenType.COMMA):
                    if self.check(TokenType.RIGHT_PAREN):
                        break
                    bases.append(self.consume(TokenType.IDENTIFIER, "Expected base class name"))
            self.consume(TokenType.RIGHT_PAREN, "Expected ')' after base classes")
        
        self.consume(TokenType.COLON, "Expected ':' after class declaration")
        self.consume(TokenType.INDENT, "Expected indented class body")
        
        methods: List[stmt.Function] = []
        class_vars: List[Tuple[Token, expr.Expr]] = []
        
        while not self.check(TokenType.DEDENT) and not self.is_at_end():
            if self.match(TokenType.NEWLINE):
                continue
            
            is_static = self.match(TokenType.STATIC)
            
            if self.match(TokenType.DEF):
                method = self.parse_func_stmt(is_method=True, is_static=is_static)
                methods.append(method)
                continue
            
            if is_static:
                self._error(self.peek(), "'static' must be followed by 'def'")
            
            if self.check(TokenType.IDENTIFIER):
                var_name = self.consume(TokenType.IDENTIFIER, "Expected variable name")
                self.consume(TokenType.ASSIGN, "Expected '=' after class variable name")
                
                value = self.expression()
                self.match(TokenType.NEWLINE)
                class_vars.append((var_name, value))
                continue
            
            if self.match(TokenType.PASS):
                continue
            
            self._error(self.peek(), "Invalid statement in class body")
        
        if self.is_at_end():
            self._error(self.previous(), "Unclosed class body - expected DEDENT before end of file")
        
        self.consume(TokenType.DEDENT, "Expected end of class body (DEDENT)")
        return stmt.Class(name, bases, methods, class_vars)
    
    def parse_try_stmt(self) -> stmt.Try:
        self.consume(TokenType.COLON, "Expected ':' after 'try'")
        
        if not self.check(TokenType.INDENT):
            self._error(self.peek(), "Expected indented block after 'try:'")
        try_block = self.statement()
        
        except_blocks: List[Tuple[Optional[expr.Expr], Optional[Token], stmt.Stmt]] = []
        while self.match(TokenType.EXCEPT):
            exc_type: Optional[expr.Expr] = None
            exc_name: Optional[Token] = None
            
            if not self.check(TokenType.COLON):
                exc_type = self.expression()
                if self.match(TokenType.AS):
                    exc_name = self.consume(TokenType.IDENTIFIER, "Expected variable name after 'as'")
            self.consume(TokenType.COLON, "Expected ':' after except clause")
            
            if not self.check(TokenType.INDENT):
                self._error(self.peek(), "Expected indented block after 'except:'")
            block = self.statement()
            except_blocks.append((exc_type, exc_name, block))
        
        else_block: Optional[stmt.Stmt] = None
        if self.match(TokenType.ELSE):
            self.consume(TokenType.COLON, "Expected ':' after 'else'")
            if not self.check(TokenType.INDENT):
                self._error(self.peek(), "Expected indented block after 'else:'")
            else_block = self.statement()
        
        finally_block: Optional[stmt.Stmt] = None
        if self.match(TokenType.FINALLY):
            self.consume(TokenType.COLON, "Expected ':' after 'finally'")
            if not self.check(TokenType.INDENT):
                self._error(self.peek(), "Expected indented block after 'finally:'")
            finally_block = self.statement()
        
        if not except_blocks and finally_block is None:
            self._error(self.previous(), "Expected at least one 'except' or 'finally' after 'try' block")
        
        return stmt.Try(try_block, except_blocks, finally_block, else_block)
    
    def parse_return_stmt(self) -> stmt.Return:
        keyword = self.previous()
        value: Optional[expr.Expr] = None
        
        if not (self.check(TokenType.NEWLINE) or self.check(TokenType.DEDENT) or self.is_at_end()):
            value = self.expression()
        
        self.match(TokenType.NEWLINE)
        return stmt.Return(keyword, value)
    
    def parse_import_stmt(self) -> stmt.Import:
        keyword = self.previous()
        module_path = self._parse_module_path()
        alias: Optional[Token] = None
        if self.match(TokenType.AS):
            alias = self.consume(TokenType.IDENTIFIER, "Expected alias name after 'as'")
        
        self.match(TokenType.NEWLINE)
        return stmt.Import(keyword, module_path, alias, names=None)
    
    def parse_from_import_stmt(self) -> stmt.Import:
        keyword = self.previous()
        module_path = self._parse_module_path()
        self.consume(TokenType.IMPORT, "Expected 'import' after module name")
        
        names: List[Tuple[Token, Optional[Token]]] = []
        while True:
            name = self.consume(TokenType.IDENTIFIER, "Expected name to import")
            alias: Optional[Token] = None
            if self.match(TokenType.AS):
                alias = self.consume(TokenType.IDENTIFIER, "Expected alias name after 'as'")
            names.append((name, alias))
            if not self.match(TokenType.COMMA):
                break
        
        self.match(TokenType.NEWLINE)
        return stmt.Import(keyword, module_path, alias=None, names=names)
    
    def _parse_module_path(self) -> List[Token]:
        parts: List[Token] = []
        parts.append(self.consume(TokenType.IDENTIFIER, "Expected module name"))
        while self.check(TokenType.DOT) and self.peek_next().type == TokenType.IDENTIFIER:
            self.advance()
            parts.append(self.consume(TokenType.IDENTIFIER, "Expected module name after '.'"))
        return parts
    
    def parse_raise_stmt(self) -> stmt.Raise:
        keyword = self.previous()
        exception = None
        if not (self.check(TokenType.NEWLINE) or self.check(TokenType.DEDENT) or self.is_at_end()):
            exception = self.expression()
        self.match(TokenType.NEWLINE)
        return stmt.Raise(keyword, exception)
    
    def parse_del_stmt(self) -> stmt.Del:
        keyword = self.previous()
        targets: List[expr.Expr] = []
        
        targets.append(self.expression())
        while self.match(TokenType.COMMA):
            targets.append(self.expression())
        self.match(TokenType.NEWLINE)
        return stmt.Del(keyword, targets)
    
    def parse_match_stmt(self) -> stmt.Match:
        keyword = self.previous()
        subject = self.expression()
        self.consume(TokenType.COLON, "Expected ':' after match subject")
        self.match(TokenType.NEWLINE)
        self.consume(TokenType.INDENT, "Expected indented block after 'match:'")
        
        cases = []
        while not self.check(TokenType.DEDENT) and not self.is_at_end():
            if self.match(TokenType.NEWLINE):
                continue
            self.consume(TokenType.CASE, "Expected 'case' in match block")
            pattern = self.parse_pattern()
            
            guard = None
            if self.match(TokenType.IF):
                guard = self.expression()
            
            self.consume(TokenType.COLON, "Expected ':' after case pattern")
            body = self._expect_indented_block()
            cases.append((pattern, guard, body))
        
        self.consume(TokenType.DEDENT, "Expected end of match block")
        return stmt.Match(keyword, subject, cases)
    
    def parse_pattern(self):
        if self.check(TokenType.IDENTIFIER) and self.peek().lexeme == "_":
            return self.advance()
        
        if self.check(TokenType.IDENTIFIER) and not self._is_pattern_literal():
            return self.advance()
        
        if self.match(TokenType.LEFT_BRACKET):
            patterns = []
            if not self.check(TokenType.RIGHT_BRACKET):
                patterns.append(self.parse_pattern())
                while self.match(TokenType.COMMA):
                    if self.check(TokenType.RIGHT_BRACKET):
                        break
                    patterns.append(self.parse_pattern())
            self.consume(TokenType.RIGHT_BRACKET, "Expected ']' after sequence pattern")
            return ("sequence", patterns)
        
        if self.match(TokenType.LEFT_BRACE):
            pairs = []
            if not self.check(TokenType.RIGHT_BRACE):
                while True:
                    key = self.expression()
                    self.consume(TokenType.COLON, "Expected ':' in mapping pattern")
                    val_pattern = self.parse_pattern()
                    pairs.append((key, val_pattern))
                    if not self.match(TokenType.COMMA):
                        break
            self.consume(TokenType.RIGHT_BRACE, "Expected '}' after mapping pattern")
            return ("mapping", pairs)
        
        node = self.expression()
        if self.match(TokenType.BAR):
            alternatives = [node]
            alternatives.append(self.expression())
            while self.match(TokenType.BAR):
                alternatives.append(self.expression())
            return ("or", alternatives)
        
        return node
    
    def _is_pattern_literal(self) -> bool:
        next_type = self.peek_next().type
        return next_type in (
            TokenType.DOT,
            TokenType.LEFT_PAREN,
        )
    
    def expression(self) -> expr.Expr:
        return self.assignment()
    
    def is_unpack_assignment(self) -> bool:
        saved = self.current
        try:
            if self.tokens[self.current].type != TokenType.IDENTIFIER:
                return False
            self.current += 1
            
            if self.tokens[self.current].type != TokenType.COMMA:
                return False
            
            while self.tokens[self.current].type == TokenType.COMMA:
                self.current += 1
                if self.tokens[self.current].type != TokenType.IDENTIFIER:
                    return False
                self.current += 1
            
            return self.tokens[self.current].type == TokenType.ASSIGN
        finally:
            self.current = saved
    
    def parse_unpack_stmt(self) -> stmt.Expression:
        names = []
        names.append(self.consume(TokenType.IDENTIFIER, "Expected identifier"))
        
        while self.match(TokenType.COMMA):
            names.append(self.consume(TokenType.IDENTIFIER, "Expected identifier after ','"))
        self.consume(TokenType.ASSIGN, "Expected '=' after unpack targets")
        
        value = self.expression()
        self.match(TokenType.NEWLINE)
        return stmt.Expression(expr.Unpack(names, value))
    
    def assignment(self) -> expr.Expr:        
        left = self.pipeline()
        
        if self.match(TokenType.IF):
            condition = self.expression()
            self.consume(TokenType.ELSE, "Expected 'else' in ternary expression")
            otherwise = self.assignment()
            return expr.Ternary(left, condition, otherwise)
        
        # Augmented assignment operators
        aug_map = {
            TokenType.PLUS_EQUAL: "+",
            TokenType.MINUS_EQUAL: "-",
            TokenType.STAR_EQUAL: "*",
            TokenType.SLASH_EQUAL: "/",
            TokenType.PERCENT_EQUAL: "%",
        }
        
        for token_type, op_str in aug_map.items():
            if self.match(token_type):
                op_token = self.previous()
                bin_op = Token(
                    type={
                        "+": TokenType.PLUS, "-": TokenType.MINUS, "*": TokenType.STAR,
                        "/": TokenType.SLASH, "%": TokenType.MODULUS,
                    }[op_str],
                    lexeme=op_str,
                    literal=None,
                    line=op_token.line,
                    column=getattr(op_token, "column", 0),
                )
                value = self.assignment()
                
                if isinstance(left, expr.Variable):
                    rhs = expr.Binary(left, bin_op, value)
                    return expr.Assign(left.name, rhs)
                
                if isinstance(left, expr.MemberAccess):
                    rhs = expr.Binary(left, bin_op, value)
                    return expr.SetMember(left.object, left.name, rhs)
                
                if isinstance(left, expr.Index):
                    rhs = expr.Binary(left, bin_op, value)
                    return expr.SetIndex(left.object, left.index, rhs)
                
                self._error(op_token, "Invalid augmented assignment target")
        
        # Regular assignment
        if self.match(TokenType.ASSIGN):
            value = self.assignment()
            
            # a = 5
            if isinstance(left, expr.Variable):
                node = expr.Assign(left.name, value)
            # obj.x = 5
            elif isinstance(left, expr.MemberAccess):
                node = expr.SetMember(left.object, left.name, value)
            # a[0] = 5
            elif isinstance(left, expr.Index):
                node = expr.SetIndex(left.object, left.index, value)
            else:
                self._error(self.previous(), "Invalid assignment target")
            
            if self.check(TokenType.NUMBER) or self.check(TokenType.STRING) or self.check(TokenType.IDENTIFIER):
                self._error(self.peek(), "Unexpected token after assignment")
            
            return node
        
        return left
    
    def pipeline(self) -> expr.Expr:
        node = self.logic_or()
        
        while self.match(TokenType.PIPE):
            right = self.logic_or()
            node = expr.Pipe(node, right)
        
        return node
    
    def logic_or(self) -> expr.Expr:
        node = self.logic_and()
        
        while self.match(TokenType.OR):
            op = self.previous()
            right = self.logic_and()
            node = expr.Logical(node, op, right)
        
        return node
    
    def logic_and(self) -> expr.Expr:
        node = self.equality()
        
        while self.match(TokenType.AND):
            op = self.previous()
            right = self.equality()
            node = expr.Logical(node, op, right)
        
        return node
    
    def equality(self) -> expr.Expr:
        node = self.comparison()
        
        while True:
            if self.match(TokenType.EQUALITY, TokenType.BANG_EQUAL):
                op = self.previous()
                right = self.comparison()
                node = expr.Binary(node, op, right)
            
            elif self.match(TokenType.IN):
                op = self.previous()
                right = self.comparison()
                node = expr.Binary(node, op, right)
            
            elif self.match(TokenType.IS):
                op = self.previous()
                if self.match(TokenType.NOT):
                    op = Token(
                        TokenType.IS,
                        lexeme="is not",
                        literal=None,
                        line=op.line,
                        column=getattr(op, "column", 0),
                    )
                right = self.comparison()
                node = expr.Binary(node, op, right)
            
            elif self.match(TokenType.NOT):
                if self.match(TokenType.IN):
                    op = Token(
                        type=TokenType.NOT,
                        lexeme="not in",
                        literal=None,
                        line=self.previous().line,
                        column=getattr(self.previous(), "column", 0),
                    )
                    right = self.comparison()
                    node = expr.Binary(node, op, right)
                else:
                    self.current -= 1
                    break
            
            else:
                break
        
        return node
    
    def comparison(self) -> expr.Expr:
        node = self.addition()
        
        while self.match(
            TokenType.GREATER, TokenType.GREATER_EQUAL,
            TokenType.LESS, TokenType.LESS_EQUAL,
        ):
            op = self.previous()
            right = self.addition()
            node = expr.Binary(node, op, right)
            
            while self.match(
                TokenType.GREATER, TokenType.GREATER_EQUAL,
                TokenType.LESS, TokenType.LESS_EQUAL,
            ):
                next_op = self.previous()
                next_right = self.addition()
                prev_right = node.right if isinstance(node, expr.Binary) else right
                next_cmp = expr.Binary(prev_right, next_op, next_right)
                and_tok = Token(
                    type=TokenType.AND,
                    lexeme="and",
                    literal=None,
                    line=next_op.line,
                    column=getattr(next_op, "column", 0),
                )
                
                node = expr.Logical(node, and_tok, next_cmp)
                right = next_right
        
        return node
    
    def addition(self) -> expr.Expr:
        node = self.multiplication()
        
        while self.match(TokenType.PLUS, TokenType.MINUS):
            op = self.previous()
            right = self.multiplication()
            node = expr.Binary(node, op, right)
        
        return node
    
    def multiplication(self) -> expr.Expr:
        node = self.unary()
        
        while self.match(
            TokenType.STAR,
            TokenType.SLASH,
            TokenType.MODULUS,
            TokenType.INT_DIVIDE,
            TokenType.AT,
        ):
            op = self.previous()
            right = self.unary()
            node = expr.Binary(node, op, right)
        
        return node
    
    def unary(self) -> expr.Expr:
        if self.match(TokenType.MINUS, TokenType.NOT):
            op = self.previous()
            right = self.unary()
            return expr.Unary(op, right)
        
        return self.power()
    
    def power(self) -> expr.Expr:
        node = self.call()
        
        if self.match(TokenType.STAR_STAR):
            op = self.previous()
            right = self.unary()
            node = expr.Binary(node, op, right)
        
        return node
    
    def call(self) -> expr.Expr:
        expr_node = self.primary()
        
        while True:
            if self.match(TokenType.LEFT_PAREN):
                arguments: List[expr.Expr] = []
                keyword_arguments: List[Tuple[Token, expr.Expr]] = []
                
                if not self.check(TokenType.RIGHT_PAREN):
                    while True:
                        if self.check(TokenType.IDENTIFIER) and self.peek_next().type == TokenType.ASSIGN:
                            kw_name = self.advance()
                            self.consume(TokenType.ASSIGN, "Expected '=' after keyword argument name")
                            kw_value = self.expression()
                            keyword_arguments.append((kw_name, kw_value))
                        else:
                            if keyword_arguments:
                                self._error(self.peek(), "Positional argument cannot follow keyword argument")
                            arguments.append(self.expression())
                        if not self.match(TokenType.COMMA):
                            break
                
                paren = self.consume(TokenType.RIGHT_PAREN, "Expected ')' after arguments")
                expr_node = expr.Call(expr_node, paren, arguments, keyword_arguments)
            
            elif self.match(TokenType.DOT):
                name = self.consume(TokenType.IDENTIFIER, "Expected property name after '.'")
                expr_node = expr.MemberAccess(expr_node, name)
            
            elif self.match(TokenType.LEFT_BRACKET):
                indices = []
                indices.append(self.parse_index_or_slice())
                
                while self.match(TokenType.COMMA):
                    indices.append(self.parse_index_or_slice())
                
                self.consume(TokenType.RIGHT_BRACKET, "Expected ']' after index")
                
                if len(indices) == 1 and not isinstance(indices[0], expr.Slice):
                    expr_node = expr.Index(expr_node, indices[0])
                else:
                    expr_node = expr.MultiIndex(expr_node, indices)
            
            else:
                break
        
        return expr_node
    
    def primary(self) -> expr.Expr:
        if self.match(TokenType.LEFT_BRACE):
            return self.parse_dict_literal()
        
        if self.match(TokenType.LEFT_BRACKET):
            if self.check(TokenType.RIGHT_BRACKET):
                self.advance()
                return expr.List([])
            
            first = self.logic_or()
            
            if self.match(TokenType.FOR):
                var = self.consume(TokenType.IDENTIFIER, "Expected variable after 'for'")
                self.consume(TokenType.IN, "Expected 'in' after loop variable")
                iterable = self.logic_or()
                condition = None
                if self.match(TokenType.IF):
                    condition = self.logic_or()
                self.consume(TokenType.RIGHT_BRACKET, "Expected ']' after list comprehension")
                return expr.ListComp(first, var, iterable, condition)
            
            elements = [first]
            while self.match(TokenType.COMMA):
                if self.check(TokenType.RIGHT_BRACKET):
                    break
                elements.append(self.expression())
            
            self.consume(TokenType.RIGHT_BRACKET, "Expected ']' after list literal")
            return expr.List(elements)
        
        if self.match(TokenType.TENSOR_LITERAL):
            token = self.previous()
            
            def parse_tensor_value(node):
                if isinstance(node, py_ast.Constant):
                    return node.value
                if isinstance(node, py_ast.Name) and node.id == "NaN":
                    return float('nan')
                if isinstance(node, py_ast.UnaryOp) and isinstance(node.op, py_ast.USub):
                    return -parse_tensor_value(node.operand)
                if isinstance(node, py_ast.List):
                    return [parse_tensor_value(el) for el in node.elts]
                raise ValueError(f"Unsupported tensor value: {py_ast.dump(node)}")
            
            try:
                tree = py_ast.parse(token.literal, mode='eval')
                raw = parse_tensor_value(tree.body)
            except Exception:
                self._error(token, "Invalid tensor literal")
            return expr.Tensor(raw)
        
        if self.match(TokenType.SELF):
            return expr.Variable(self.previous())
        
        if self.match(TokenType.NULL):
            return expr.Literal(None)
        
        if self.match(TokenType.LAMBDA):
            return self.parse_lambda()
        
        if self.match(TokenType.FSTRING):
            return self.parse_fstring(self.previous())
        
        if self.match(TokenType.NUMBER, TokenType.STRING, TokenType.BOOL):
            return expr.Literal(self.previous().literal)
        
        if self.match(TokenType.IDENTIFIER):
            return expr.Variable(self.previous())
        
        if self.match(TokenType.LEFT_PAREN):
            expr_node = self.expression()
            self.consume(TokenType.RIGHT_PAREN, "Expected ')' after expression")
            return expr_node
        
        self._error(self.peek(), f"Unexpected token '{self.peek().lexeme}' - expected an expression")
        raise AssertionError("unreachable")
    
    def parse_dict_literal(self) -> expr.Dict:
        keys: List[expr.Expr] = []
        values: List[expr.Expr] = []
        
        if not self.check(TokenType.RIGHT_BRACE):
            while True:
                key = self.expression()
                self.consume(TokenType.COLON, "Expected ':' after dict key")
                value = self.expression()
                keys.append(key)
                values.append(value)
                if not self.match(TokenType.COMMA):
                    break
                if self.check(TokenType.RIGHT_BRACE):
                    break
        
        self.consume(TokenType.RIGHT_BRACE, "Expected '}' after dict entries")
        return expr.Dict(keys, values)
    
    def parse_fstring(self, token) -> expr.FString:
        raw: str = token.literal
        parts: List[expr.Expr] = []
        i = 0
        length = len(raw)
        
        while i < length:
            start = raw.find("{", i)
            
            if start == -1:
                if i < length:
                    parts.append(expr.Literal(raw[i:]))
                break
            
            if start > i:
                parts.append(expr.Literal(raw[i:start]))
            
            depth = 1
            j = start + 1
            while j < length and depth > 0:
                if raw[j] == "{":
                    depth += 1
                elif raw[j] == "}":
                    depth -= 1
                j += 1
            
            if depth != 0:
                self._error(token, "Unclosed '{' in f-string")
            
            fragment = raw[start+1 : j-1].strip()
            if not fragment:
                self._error(token, "Empty expression '{}' in f-string")
            
            inner_tokens = Lexer(fragment).scan_tokens()
            inner_parser = Parser(inner_tokens, fragment)
            parts.append(inner_parser.expression())
            
            i = j
        
        return expr.FString(parts)
    
    def parse_index_or_slice(self) -> expr.Expr:
        if self.check(TokenType.COLON):
            self.advance()
            upper = None
            if not self.check(TokenType.RIGHT_BRACKET) and not self.check(TokenType.COMMA):
                upper = self.expression()
            return expr.Slice(None, upper)
        
        lower = self.expression()
        
        if self.match(TokenType.COLON):
            upper = None
            if not self.check(TokenType.RIGHT_BRACKET) and not self.check(TokenType.COMMA):
                upper = self.expression()
            return expr.Slice(lower, upper)
        
        return lower
    
    def parse_lambda(self) -> expr.Expr:
        params: List[Token] = []
        
        if not self.check(TokenType.COLON):
            params.append(self.consume(TokenType.IDENTIFIER, "Expected paramater name"))
            while self.match(TokenType.COMMA):
                if self.check(TokenType.COLON):
                    break
                params.append(self.consume(TokenType.IDENTIFIER, "Expected paramater name"))
        
        self.consume(TokenType.COLON, "Expected ':' after lambda parameters")
        body = self.expression()
        return expr.Lambda(params, body)